# Generated by devenv: Nix store path remappings and PATH entries.
export NIX_CFLAGS_COMPILE="-fmacro-prefix-map=/nix/store/l9r346p3d25vs4g5v37f3r3f28js97kb-libresolv-96-dev=/nix/store/6cp643dzvlxxpkgbg5kzmwj47sam9zs2-libresolv-96"
export PATH="/nix/store/4lmnzx45iy43kwjqn1xna7z3dj8grrz5-coreutils-9.5/bin:/nix/store/awri8visnqf95b9ff0zbhj09spl83xrr-bash-5.2/bin:$PATH"
export NIX_LDFLAGS="-L/nix/store/6cp643dzvlxxpkgbg5kzmwj47sam9zs2-libresolv-96/lib"
